// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// soft_threshold_cpp
arma::vec soft_threshold_cpp(const arma::vec& x, double lambda);
RcppExport SEXP _scadLLA_soft_threshold_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_threshold_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// solve_dynamic_lqa_admm_cpp
arma::mat solve_dynamic_lqa_admm_cpp(const List& y_list, const List& X_list, const arma::mat& w_mat, double lambda, double tau, double rho, int max_iter, double tol);
RcppExport SEXP _scadLLA_solve_dynamic_lqa_admm_cpp(SEXP y_listSEXP, SEXP X_listSEXP, SEXP w_matSEXP, SEXP lambdaSEXP, SEXP tauSEXP, SEXP rhoSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type w_mat(w_matSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_dynamic_lqa_admm_cpp(y_list, X_list, w_mat, lambda, tau, rho, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// generate_X_cpp
arma::mat generate_X_cpp(int n, int p, double rho);
RcppExport SEXP _scadLLA_generate_X_cpp(SEXP nSEXP, SEXP pSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_X_cpp(n, p, rho));
    return rcpp_result_gen;
END_RCPP
}
// generate_epsilon_cpp
arma::vec generate_epsilon_cpp(int n, double sigma, double rho_eps);
RcppExport SEXP _scadLLA_generate_epsilon_cpp(SEXP nSEXP, SEXP sigmaSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_epsilon_cpp(n, sigma, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_beta_error_cpp
double compute_beta_error_cpp(const arma::mat& beta_est, const arma::mat& beta_true);
RcppExport SEXP _scadLLA_compute_beta_error_cpp(SEXP beta_estSEXP, SEXP beta_trueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_est(beta_estSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_true(beta_trueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_beta_error_cpp(beta_est, beta_true));
    return rcpp_result_gen;
END_RCPP
}
// compute_prediction_mse_cpp
double compute_prediction_mse_cpp(const arma::mat& beta_est, const List& X_list, const List& y_list);
RcppExport SEXP _scadLLA_compute_prediction_mse_cpp(SEXP beta_estSEXP, SEXP X_listSEXP, SEXP y_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_est(beta_estSEXP);
    Rcpp::traits::input_parameter< const List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_prediction_mse_cpp(beta_est, X_list, y_list));
    return rcpp_result_gen;
END_RCPP
}
// compute_covariance_error_cpp
double compute_covariance_error_cpp(const arma::mat& beta_est, const List& X_list, const arma::mat& beta_true, double sigma, double rho_eps);
RcppExport SEXP _scadLLA_compute_covariance_error_cpp(SEXP beta_estSEXP, SEXP X_listSEXP, SEXP beta_trueSEXP, SEXP sigmaSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_est(beta_estSEXP);
    Rcpp::traits::input_parameter< const List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_true(beta_trueSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_covariance_error_cpp(beta_est, X_list, beta_true, sigma, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_mv_return_cpp
double compute_mv_return_cpp(const arma::mat& beta_est, const List& X_list, const List& y_list, double sigma, double rho_eps);
RcppExport SEXP _scadLLA_compute_mv_return_cpp(SEXP beta_estSEXP, SEXP X_listSEXP, SEXP y_listSEXP, SEXP sigmaSEXP, SEXP rho_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_est(beta_estSEXP);
    Rcpp::traits::input_parameter< const List& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_eps(rho_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mv_return_cpp(beta_est, X_list, y_list, sigma, rho_eps));
    return rcpp_result_gen;
END_RCPP
}
// generate_time_series_data_cpp
List generate_time_series_data_cpp(int T_periods, int n_per_period, int p, double rho, double rho_eps, double sigma);
RcppExport SEXP _scadLLA_generate_time_series_data_cpp(SEXP T_periodsSEXP, SEXP n_per_periodSEXP, SEXP pSEXP, SEXP rhoSEXP, SEXP rho_epsSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T_periods(T_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type n_per_period(n_per_periodSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_eps(rho_epsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_time_series_data_cpp(T_periods, n_per_period, p, rho, rho_eps, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scadLLA_soft_threshold_cpp", (DL_FUNC) &_scadLLA_soft_threshold_cpp, 2},
    {"_scadLLA_solve_dynamic_lqa_admm_cpp", (DL_FUNC) &_scadLLA_solve_dynamic_lqa_admm_cpp, 8},
    {"_scadLLA_generate_X_cpp", (DL_FUNC) &_scadLLA_generate_X_cpp, 3},
    {"_scadLLA_generate_epsilon_cpp", (DL_FUNC) &_scadLLA_generate_epsilon_cpp, 3},
    {"_scadLLA_compute_beta_error_cpp", (DL_FUNC) &_scadLLA_compute_beta_error_cpp, 2},
    {"_scadLLA_compute_prediction_mse_cpp", (DL_FUNC) &_scadLLA_compute_prediction_mse_cpp, 3},
    {"_scadLLA_compute_covariance_error_cpp", (DL_FUNC) &_scadLLA_compute_covariance_error_cpp, 5},
    {"_scadLLA_compute_mv_return_cpp", (DL_FUNC) &_scadLLA_compute_mv_return_cpp, 5},
    {"_scadLLA_generate_time_series_data_cpp", (DL_FUNC) &_scadLLA_generate_time_series_data_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_scadLLA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
